version: '3.8'

services:
  sofa-commander:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GIN_MODE=release
    volumes:
      # 掛載配置檔案，方便開發時修改
      - ./backend/config:/app/config:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 